config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :categories, only: [:index]

  namespace :admin do
    resources :categories do
      resources :words, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    end
  end

  resources :words do
    resources :choices, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/category.rb
class Category < ApplicationRecord

    has_many :words, dependent: :destroy
    accepts_nested_attributes_for :words

    default_scope -> { order('created_at DESC') }

    validates :title, presence: true, length: { minimum: 2 }
    validates :description, presence: true, length: {maximum: 140}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :if_not_admin
  
   def new
     @category = Category.new
     @category.words.build
   end

   def create
     if Category.create(category_params)
       redirect_to admin_categories_path
       flash[:success] = "Created successfully!"
     else
       flash[:danger] = "Invalid"
       render 'new'
     end  
   end
   
   def show
    @category = Category.find(params[:id])
    # @word = @category.words.find(params[:id])
   end

   def edit
    @category = Category.find(params[:id])
   end

   def update
     @category = Category.find(params[:id])
     if @category.update_attributes(category_params)
       redirect_to admin_categories_path
       flash[:success] = "Saved!"
     else
       flash[:danger] = "Invalid"
       render 'edit'
     end
   end  

  def index
    @category = Category.select('id','title', 'description')
    @id = Category.select('id')
  end

  def destroy
    Category.find(params[:id]).destroy
    redirect_to admin_categories_path
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def category_params
    params.require(:category).permit(:title, :description, words_attributes: [:words, :category_id])
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
     def index
       @category = Category.select('id','title', 'description')
       @id = Category.select('id')
     end
  end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<% provide(:title, 'Edit | Manage Categories') %>
<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Edit Category</h3>
        </div>
    </div>
</div>

<div id="service">
    <div class="container">
    <%= form_for [:admin, @category] do |f| %>
        <div class="field">
            <%= f.text_area :title, placeholder: "title", class: "w-100 p-2" %>
            <%= f.text_area :description, placeholder: "description", class: "w-100 p-2" %>
        </div>
        <%= f.submit "Post", class: "btn btn-block btn-primary" %>
    <% end %>
    </div>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, 'Manage Categories') %>
<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Category List</h3>
        </div>
    </div>
</div>

<div id="service">
    <div class="container">
    <h4>There are <%= @id.count %> categories now.</h4>
    <button type="button" class="btn btn-success btn-lg mb-3"><%= link_to "Create New Category!", new_admin_category_path %></button>
        <div class="centered">
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Category ID</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">total of Words</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @category.each do |category| %>
    <tr>
      <th scope="row"><%= category.id %></th>
      <td><%= link_to category.title, admin_category_path(category)  %></td>
      <td><%= category.description %></td>
      <td><%= category.words.ids.count %></td>
      <td><button type="button" class="btn btn-warning mr-1">
      <%= link_to 'Edit', edit_admin_category_path(category) %></button>
      <button type="button" class="btn btn-secondary">
      <%= link_to 'Delete', admin_category_path(category), method: :delete,
      data: { confirm: "You sure?" } %></button></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>
    </div>
</div>

app/views/admin/categories/new.html.erb
<% provide(:title, 'New | Manage Categories') %>
<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Create NEW Category</h3>
        </div>
    </div>
</div>

<div id="service">
    <div class="container">
    <%= form_for [:admin, @category] do |f| %>
        <div class="field">
            <%= f.text_area :title, placeholder: "title", class: "w-100 p-2" %>
            <%= f.text_area :description, placeholder: "description", class: "w-100 p-2" %>
        </div>
        <%= f.submit "Post", class: "btn btn-block btn-primary" %>
    <% end %>
    </div>
</div>

app/views/admin/categories/show.html.erb
<% provide(:title, @category.title) %>
<div id="blue">
    <div class="container">
        <div class="row">
            <h3>Category > Word</h3>
        </div>
    </div>
</div>

<div id="service">
    <div class="container">
        <h4>ID: <%= @category.id %> | Title: <%= @category.title %></h4>
        <p>description: <%= @category.description %></p>
        <p style="text-align:right"><%= link_to "Back to Category list", admin_categories_path %></p>
        <% if @category.words.any? %>

        <button type="button" class="btn btn-success btn-lg mb-3">
          <%= link_to "Create New Word!", new_admin_category_word_path(@category) %></button>
        
        <div class="centered">
          <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Word ID</th>
                <th scope="col">Title</th>
                <th scope="col">Action</th>
              </tr>
            </thead>
            
            <tbody>
              <% @category.words.each do |word| %>
              <tr>
                <th scope="row"><%= word.id %></th>
                <td><%= word.words %></td>
                <td>
                  <button type="button" class="btn btn-warning mr-1">
                    <%= link_to 'Edit', edit_admin_category_word_path(@category, word) %></button>
                  <button type="button" class="btn btn-secondary">
                    <%= link_to 'Delete', admin_category_word_path(@category, word), method: :delete, data: { confirm: "You sure?" } %></button>
                </td>
              </tr>
              <% end %>
            </tbody>            
          </table>
        </div>
        <% else %>
        <div class="centered">
          <h4>Nothing is registered.</h4>
          <button type="button" class="btn btn-success btn-lg mt-3 mb-3">
          <%= link_to "Create New Word!", new_admin_category_word_path(@category) %></button>
        </div> 
        <% end %>
    </div>
</div>