config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'

  get '/signup', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers
    end
  end
  
  resources :categories, only: [:index]

  namespace :admin do
    resources :categories do
      resources :words, only: [:index, :new, :create, :show, :edit, :update, :destroy]
    end
  end

  resources :words do
    resources :choices, only: [:new, :create, :edit, :update, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

    has_many :words, dependent: :destroy
    accepts_nested_attributes_for :words

    default_scope -> { order('created_at DESC') }

    validates :title, presence: true, length: { minimum: 2 }
    validates :description, presence: true, length: {maximum: 140}
end

app/models/choice.rb
class Choice < ApplicationRecord
    belongs_to :word, foreign_key: "word_id"

    validates :choices, presence: true, length: { minimum: 1 }
    validates :correct_ans, inclusion: { in: [true, false] }

end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # user name
  validates :name, presence: true, length: { minimum: 5 }

  # user email
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
             uniqueness: { case_sensitive: false }
  # user password
  validates :password, length: { minimum: 5}
  has_secure_password

  # Followed Users
  has_many :active_relationships, foreign_key: "follower_id",
                                  class_name: "Relationship",
                                  dependent:  :destroy
  # user.active_relationships.followed_id -> user.followed_users
  has_many :followed_users, through: :active_relationships, source: :followed

  # Followers
  has_many :passive_relationships, foreign_key: "followed_id", # no conflict becauser they have diffrent FK
                                   class_name: "Relationship", # able to use the same table
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower

  # Returns true if the current user is following the other user
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end
  
  # Follows a user
  def follow(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  # Unfollows a user
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  def active_user?
    active_relationships.find_by(admin_user: id)
  end  
  
end

app/models/word.rb
class Word < ApplicationRecord
    belongs_to :category, foreign_key: "category_id"

    has_many :choices, dependent: :destroy
    accepts_nested_attributes_for :choices
    
    default_scope -> { order('created_at ASC') }

    validates :words, presence: true, length: { maximum:200 }

    validates :category_id, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
     def index
       @category = Category.select('id','title', 'description')
       @id = Category.select('id')
     end
  end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :only_loggedin_users

    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
        respond_to do |format|
            format.html { redirect_to @user }
            format.js
        end    
    end

    def destroy
        @user = Relationship.find(params[:id]).followed
        current_user.unfollow(@user)
        respond_to do |format|
            format.html { redirect_to @user }
            format.js
        end    
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
        flash[:success] = "Successfully logged in!"
        log_in user
        redirect_to root_url
    else
        render 'new'
        flash.now[:danger] = "Invalid content. Try again."  
    end
  end

  def destroy
    log_out
        
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # FILTER
  before_action :only_loggedin_users, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Saved successfully!"   
      redirect_to login_url
    else
      flash[:danger] = "Invalid content. Try again."
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @word = Word.find(params[:id])
  end

  def index
    # @users = User.all
    @users = User.paginate(page: params[:page], per_page: 12)
    # @user = User.find(params[:other_user.id])
  end

  def edit
    @user = User.find(params[:id])
  end 

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Saved successfully!"
      redirect_to @user
    else
      flash[:danger] = "Invalid content. Try again."
      render 'edit'  
    end  
  end  

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page], per_page: 5)
    @all_users = @user.followed_users
    render 'show_follow'
  end
  
  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page], per_page: 5)
    @all_users = @user.followers
    render 'show_follow'    
  end  

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def correct_user
    # You cannot access this page UNLESS you are the current user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
  
end

app/helpers/admin/words_helper.rb
module Admin::WordsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
    
  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
    
  # Returns the current logged-in user (if any).
  def current_user # after log_in -> current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil? # is there NO EMPTY current_user? Is there a current_user?
    # is the current user empty? TRUE
    # is the current user NOT empty? FALSE
  end
    
  # Logs out the current user.
  def log_out
    session.delete(:user_id) # deletes memory in browser
    @current_user = nil       # deletes you as current_user
  end
    
  def only_loggedin_users
    redirect_to login_url unless logged_in?
  end
      
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/_footer.html.erb
<div id="copyrights">
    <div class="container">
        <p>
            &copy; Copyrights <strong>Elearning</strong>. All Rights Reserved
        </p>
    </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Elearning</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "About", about_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Contact us", contact_path, class: "nav-link" %>
                </li>
                
                <% if logged_in? %>
                <%# THERE IS A CURRENT USER %>
                    <% if current_user.admin? %>
                    <li class="nav-item">
                        <%= link_to "Manage Categories", admin_categories_path, class: "nav-link" %>
                    </li>
                    <% end %>
                <li>
                    <%= link_to "Categories", categories_path, class: "nav-link" %>
                </li>
                <li>
                    <%= link_to "Users", users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        <%= current_user.name %> <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li>
                            <%= link_to "Profile", current_user, class: "dropdown-item" %>
                        </li>
                        <li>
                            <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
                        </li>
                        <li class="divider">
                        </li>
                        <li>
                            <%= link_to "Sign out", logout_path, method: :delete, class: "dropdown-item" %>
                        </li>
                    </ul>
                </li>
                <% else %>
                <%# EMPTY USER -> no current user %>
                <li class="nav-item">
                    <%= link_to "Signup", signup_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login", login_path, class: "nav-link" %>
                </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= yield(:title) %> | Elearning</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- Google Fonts -->
        <link href="https://fonts.googleapis.com/css?family=Raleway:400,700,900|Lato:400,900" rel="stylesheet">
    </head>

    <body>
        <%= render 'layouts/header' %>
        <%= render 'shared/error_messages' %>        
        <%= yield %>
        <%= render 'layouts/footer' %>
    </body>
</html>

app/views/shared/_category_form.html.erb
<%= form_for(@category) do |f| %>
    <div class="field">
        <%= f.text_area :title, placeholder: "title", class: "w-100 p-2" %>
        <%= f.text_area :description, placeholder: "description", class: "w-100 p-2" %>
    </div>
    <%= f.submit "Post", class: "btn btn-block btn-primary" %>
<% end %>

app/views/shared/_error_messages.html.erb
<% flash.each do |type, msg| %>
    <% if type == "danger" %>
        <div class="alert alert-danger alert-dismissible fade show mt-4" role="alert">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% else %>
        <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
            <strong><%= msg %></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">

        <strong id="following" class="stat">
            <%= @user.followed_users.count %>
        </strong>
        following

        <strong id="followers" class="stat">
            <%= @user.followers.count %>
        </strong>
        followers
                
</div>